### ISSUE TITLE
Merge the fork source

### ISSUE THREAD

**Issue by knownasilya** [Strider-CD/strider-gitlab#7]
Seems like the original author, @meric426 is making updates on his version. Should we have one repo only, for the sake of the users sanity and our debugging.

We have 1.0.4 and the author 1.0.5.. plus the author has his published on npm as `strider-gitlab`.

**Comment by marcuspoehls** [comment]
Actually, it would be really great to merge this fork and the original repository of @meric426. I mean, we definitely need to find a solution for this issue of parallel repositories with different maintainers.

The [last commit](https://github.com/meric426/strider-gitlab/commits/master) to the original repository was on Nov 6th 2014. Even though there have been "only" 10 commits to this fork, the updates have stabilized this plugin a lot. I would love to see a merge of both repositories with the respective npm deployment, as well.

@meric426, @knownasilya: Do you guys think we could merge both repositories so that the Strider-CD organization has the repository and not just a fork?

**Comment by knownasilya** [comment]
I'm totally for that, and we can add @meric426 as an owner or contributor to the repo.

**Comment by oliversalzburg** [comment]
Can anyone tell me what there is upstream that we don't have in the fork? I see 2 commits we don't have over here, but I can't see any problems with the current state of the provider.

If there are any issues, I'll gladly take care of them. We use strider+gitlab in production, so we're committed and able to maintain for the time being.

That being said, I'm in no way opposed to having the original author working on the plugin as well. But we require a higher level of responsiveness, which is not provided by the original project.

**Comment by knownasilya** [comment]
Nothing. I think it might be worthwhile removing the other dep from the package.json and just use the manager.

**Comment by marcuspoehls** [comment]
:+1:

**Comment by oliversalzburg** [comment]
Fixed as of https://github.com/Strider-CD/strider/commit/c4e2a1e85e97972d27a9338346362097bea18a7e

**Comment by meric426** [comment]
Sorry to comment in an old issue but i've removed my repo as root for this fork and i've added @oliversalzburg and @knownasilya as contributors to npmjs so they can publish new versions
